import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import parse from "html-react-parser";
const inter = Inter({ subsets: ["latin"] });

export default function Home({ page }) {
  // let Title = data.pageBy.title;
  // console.log(page.content);
  // console.log(JSON.parse(page.content));
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>{page.title}</h1>

        <div>{parse(page.content)}</div>
      </main>
    </>
  );
}

export async function getStaticProps() {
  const response = await fetch("https://project7m.com/graphql", {
    // Replace with your GraphQL API endpoint
    method: "POST",
    headers: {
      "Content-Type": "application/json",
    },
    body: JSON.stringify({
      query: `
        query {
          pageBy(uri: "https://project7m.com/ai-unveiled-illuminating-the-realm-of-intelligent-machines/") {
            title
            content
            featuredImage {
              node {
                mediaItemUrl
                altText
              }
            }
            # Add any additional fields you want to retrieve
          }
        }
      `,
    }),
  });

  const { data } = await response.json(); // Access the 'data' property from the response

  return {
    props: {
      page: data.pageBy, // Pass the page data as props
    },
  };
}
